import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'normalize.css'

export const metadata: Metadata = {
  title: "Unbeateble",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin", "cyrillic"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
